//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GermanyTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vertex
    {
        public int ID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public decimal Rout { get; set; }
        public decimal Time { get; set; }
        public decimal Cost { get; set; }
        public decimal RTC { get; set; }
    }
}
